[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: smoke tests
    regression: regression tests

# I was testing it on arm M processor and chromium couldn't launch... used firefox :/
addopts = --browser firefox
